### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by z38** [casperbiering/dotnet-binary-xml#1]
Under what license are you publishing your work?

**Comment by casperbiering** [comment]
Sorry for the delay. I'm publishing it under MIT. I've restructured the repo and added for support for composer/packagist and phpunit.

**Comment by z38** [comment]
Wow, thank you for the restructuring! I originally intended to fork the project in order to implement Composer support, unit tests, .... Now I think I will just submit a few PRs to improve some minor details.

**Comment by casperbiering** [comment]
You're welcome. Looking forward to the PRs :-)
